create table if not exists applicants (
    applicationid int PRIMARY KEY generated by default as identity,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(6),
    email varchar(50) unique NOT NULL,
    phone_num varchar(15),
    nationality varchar(20),
    "address" varchar(100)
);

create table if not exists admissions (
    sn int NOT NULL PRIMARY KEY generated by default as identity,
    application_id int,
    application_date TIMESTAMP,
    admission_status varchar(8),
    application_type varchar(12),
    constraint fk_admission FOREIGN KEY (application_id) references applicants(applicationid)
);

create table if not exists programs (
    program_id VARCHAR(10) unique primary key,
    program_name VARCHAR(50),
    program_level VARCHAR(15),
    duration SMALLINT
);

create table if not exists entry_requirements (
    id int NOT NULL PRIMARY KEY generated by default as identity,
    program_id VARCHAR(10),
    entry_type VARCHAR(12),
    credits smallint,
    constraint fk_entryReq FOREIGN KEY (program_id) references programs(program_id)
);

create table if not exists credits (
    id int not null primary key generated by default as identity,
    exam_name varchar(10),
    course varchar(20),
    points smallint
);